<?php
  require_once('core/CD_Config.php');
  require_once('core/CD_Controller.php');
  require_once('core/CD_Loader.php');
  require_once('core/CD_Database.php');
  require_once('core/CD_Model.php');
  require_once('config/route.php');
  require_once('helper/cd_helper.php');
?>
